name: Github Actions, Python and C++

on: [push]

jobs:
  # Python checks - pylint + pytest
  python_build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.12.11
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format

  # C++ checks (clang-dity + cppcheck)
  cpp_build:
    runs-on: ubuntu-latest

    steps:
    -uses: actions/checkout@v2
    -name: Install clang-dity and cpp check
      run: sudo apt-get update && sudo apt-get install -y clang-tidy cppcheck

    #-name: Run clang-tidy
    #  run: clang-tidy cpp_sector/*.cpp -- -std=c++17

    #-name: Run cppcheck
    # run: cppcheck --enable=all --inconclusive --errror-exitcode=1 cpp_sector/

  
